spring:
  output:
    ansi:
      enabled: ALWAYS
  main:
    banner-mode: "console"
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36}:%L - %msg%n"
  level:
    root: INFO
    com.example.demo: DEBUG


